name: test-release

on: 
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Get potential Pre-Release
        id: potential_pre_release
        uses: joutvhu/get-release@v1.0.2
        with:
          prerelease: true
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Last Release
        if: ${{ steps.potential_pre_release.outputs.prerelease == 'false' }}
        id: latest_release
        uses: joutvhu/get-release@v1.0.2
        with:
          prerelease: false
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: ${{ steps.potential_pre_release.outputs.prerelease == 'false' }}
        run: |
          echo W_RELEASE="NextVersion" >> $GITHUB_ENV

      - name: Send GitHub Action trigger data to Slack workflow
        if: ${{ steps.potential_pre_release.outputs.prerelease == 'false' }}
        id: slack
        run: echo 'release created'

      - name: Send GitHub Action trigger data to Slack workflow - skipped
        if: ${{ steps.potential_pre_release.outputs.prerelease == 'true' }}
        id: slack_skipped
        run: echo 'release skipped'